# Load data
source("data/day3_objects.R")

# Creating plots - general syntax
# ggplot(data=<DATA FRAME>) + <GEOM_FUNCTION>(mapping=aes(<VARIABLES>))

# Creating scatterplot
ggplot(data=gapminder07) + 
    geom_point(mapping=aes(x=gdpPercap, y=lifeExp))

# Add labels
ggplot(data=gapminder07) + 
    geom_point(mapping=aes(x=gdpPercap, y=lifeExp)) +
    labs(title="Relationship between life expectancy and GDP per capita",
         x="GDP per capita", y="Life expectancy")

# Class exercise #1
# create variables for the natural log of gdpPercap and pop
gapminder07$log_gdpPercap <- log(gapminder07$gdpPercap)
gapminder07$log_pop <- log(gapminder07$pop)
gapminder07$log_lifeExp <- log(gapminder07$lifeExp)

# create scatterplot
ggplot(data=gapminder07) +
    geom_point(mapping=aes(x=log(pop), y=log(gdpPercap))) +
    labs(title="Relationship between population and GDP per capita",
         x="log(population)", y="log(GDP per capita)")

# Plot total output over time
# manipulate dataframe to calculated total output per date-time
long_gen %>% 
    group_by(datetime) %>% 
    summarize(output=sum(output)) %>% 
    ggplot() + 
    geom_col(aes(x=datetime, y=output)) +
    labs(title="Total energy generated by hour", x="Hour", y="Output") +
    theme_classic()

# Class exercise - plot a column chart hydroelectric power generated over time
generation %>% 
    select(datetime, contains("hydro")) %>%
    mutate(total_hydro=large_hydro+small_hydro) %>% 
    group_by(datetime) %>% 
    summarize(total_hydro=sum(total_hydro)) %>% 
    ggplot() +
    geom_col(aes(x=datetime, y=total_hydro)) + 
    labs(title="Total hydroelectric energy generated by hour", x="Hour", y="Hydroelectric Output")

long_gen %>%
    filter(source=="large_hydro" | source=="small_hydro") %>% # filter(str_detect(source, "hydro"))
    group_by(datetime) %>%
    summarize(total_hydro=sum(output)) %>%
    ggplot() +
    geom_col(aes(x=datetime, y=total_hydro)) +
    labs(title="Total hydroelectric energy generated by hour", x="Hour", y="Hydroelectric Output")

# Other examples
# line graph, changing size and color
imports %>% 
    ggplot() +
    geom_line(aes(x=datetime, y=imports), size=1.2, col="red") +
    labs(title="Energy imports over time", x="Hour", y="Amount imported")

generation %>%
    ggplot() +
    geom_area(aes(x=datetime, y=wind), fill="darkblue") +
    labs(title="Hourly wind power generation", x="Hour", y="Output")

long_gen %>% 
    ggplot() +
    geom_boxplot(aes(x=source, y=output)) +
    labs(title="Amount of energy generated by each source", x="Source type", y="Output")

# Plot a line of large hydro generation over time and a smoothed line of the same relationship on top of it
generation %>% 
    ggplot() +
    geom_line(aes(x=datetime, y=large_hydro), col="turquoise3") +
    geom_smooth(aes(x=datetime, y=large_hydro)) +
    labs(title="Hydroelectric(large) generation per hour", x="Hour", y="Output")

# Class exercise
# create a column chart that shows the output by source
# add a horizontal line representing the mean of total output
long_gen %>%
    group_by(source) %>% 
    summarize(total_output=sum(output)) %>% 
    ggplot() +
    geom_col(aes(x=source, y=total_output), col="darkred", fill="darkred") +
    geom_hline(aes(yintercept=mean(total_output))) +
    geom_hline(aes(yintercept=median(total_output)), linetype=2, col="darkblue") +
    labs(title="Total output by energy source", x="Source", y="Output") # +
    # coord_flip()

# Add scales and themes
imports %>% 
    ggplot() +
    geom_line(aes(x=datetime, y=imports), col="red") +
    scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
    labs(title="Energy imports over time in California", subtitle="Hourly data from Sept 3-9") +
    theme(axis.text.x=element_text(angle=45, hjust=1, size=8))

# Create different lines by source
long_merged_energy %>% 
    ggplot() +
    geom_line(aes(x=datetime, y=output, group=source, col=source)) +
    labs(title="Output by energy source", x="Hour", y="Output")

# Class exercise #4
# create a line plot that compares generation of wind, solar, and geothermal energy
long_merged_energy %>% 
    filter(source %in% c("wind", "solar", "geothermal")) %>%
    ggplot() +
    geom_line(aes(x=datetime, y=output, group=source, col=source), size=1.5) +
    labs(title="Output for geothermal, solar, and wind", x="Hour", y="Output")
